fix workflow

diff --git a/.github/workflows/deploy-backend.yml b/.github/workflows/deploy-backend.yml
--- a/.github/workflows/deploy-backend.yml
+++ b/.github/workflows/deploy-backend.yml
@@ -1,10 +1,10 @@
 name: Build and Deploy Java Backend
 
 on:
-  push:
-    branches: [ "main", "feature/*" ]
-  pull_request:
-    branches: [ "main", "feature/*" ]
+    push:
+      branches: [ "main" ]
+    pull_request:
+      branches: [ "main" ]  
 
 jobs:
   build:
@@ -64,6 +64,6 @@ jobs:
       run: |
         echo "$SSH_PRIVATE_KEY" > deploy_key
         chmod 600 deploy_key
-        scp -i deploy_key -r backend/target/*.jar ibm@123.207.71.173:/opt/myapp || { echo 'SCP failed'; exit 1; }
-        ssh -i deploy_key ibm@123.207.71.173 'bash /opt/myapp/deploy.sh' || { echo 'SSH command failed'; exit 1; }
+        scp -o StrictHostKeyChecking=no -i deploy_key -r backend/target/*.jar ibm@123.207.71.173:/opt/myapp || { echo 'SCP failed'; exit 1; }
+        ssh -o StrictHostKeyChecking=no -i deploy_key ibm@123.207.71.173 'bash /opt/myapp/deploy.sh' || { echo 'SSH command failed'; exit 1; }
         rm deploy_key
